BASE=../../../..
LOCAL_SOURCES=cari_net_commonHeader.cpp cari_net_event_process.cpp cari_net_notify.cpp cari_net_socket.cpp CBaseModule.cpp CModule_NEManager.cpp  CModule_Route.cpp CModule_SysInfo.cpp CModule_User.cpp CModuleManager.cpp CMsgProcess.cpp
LOCAL_OBJS=cari_net_commonHeader.o cari_net_event_process.o cari_net_notify.o cari_net_socket.o CBaseModule.o CModule_NEManager.o  CModule_Route.o CModule_SysInfo.o CModule_User.o CModuleManager.o CMsgProcess.o
LOCAL_LDFLAGS=-lm
include $(BASE)/build/modmake.rules